### ISSUE TITLE
Not able to send empty config text field via createData operation

### ISSUE THREAD

**Issue by ameysar** [magento/magento2-functional-testing-framework#203]
Empty data (e.g. empty string) for primitive types are [skipped during generation of persist operation data](https://github.com/magento/magento2-functional-testing-framework/blob/2.2.0/src/Magento/FunctionalTestingFramework/DataGenerator/Persist/OperationDataArrayResolver.php#L114).

### Preconditions

1. Magento 2.2.x installed

### Steps to reproduce

1. Create [store_info_config-meta.xml](https://github.com/magento/magento2-functional-testing-framework/files/2301691/store_info_config-meta.txt)
2. Create [StoreConfigData.xml](https://github.com/magento/magento2-functional-testing-framework/files/2301693/StoreConfigData.txt)
3. Run test [AdminSetupStoreInformationTest.xml](https://github.com/magento/magento2-functional-testing-framework/files/4052475/AdminSetupStoreInformationTest.txt)

### Expected result

1.  Test should pass successfully

### Actual result

1. Test failed with error: **Failed asserting that a string is empty.**

**Comment by aljcalandra** [comment]
@ameysar, thanks for submitting this Github issue. We have created MQE-1218 to track this in our internal ticketing system.

**Comment by tomreece** [comment]
Link to internal issue:
https://jira.corp.magento.com/browse/MQE-1218

**Comment by lbajsarowicz** [comment]
@ameysar I believe that your issue was fixed.
Could you confirm or reproduce the issue now?

**Comment by ameysar** [comment]
@lbajsarowicz issue is not fixed. I've updated the attached test. Please try to run it.

**Comment by lbajsarowicz** [comment]
@ameysar I'll address that next weekend probably :-)

**Comment by jilu1** [comment]
@ameysar @lbajsarowicz Internal ticket is cancelled due to low priority. If you think otherwise, please feel free to reopen the issue.
